package main.resources.rules;
dialect  "mvel"

import org.kie.api.runtime.KieRuntime
import java.util.ArrayList
import javax.swing.JOptionPane
import javax.swing.JFrame

global JFrame frame
global javax.swing.JTextArea textArea

declare Choice
	question : String
	answers : String[]
	decision : String
end

function String ask(JFrame frame, Choice choice) {
        Object[] options = {choice.getAnswers()[0], choice.getAnswers()[1]};
        return choice.getAnswers()[JOptionPane.showOptionDialog(frame,
                                             choice.question,
                                             "",
                                             JOptionPane.YES_NO_OPTION,
                                             JOptionPane.QUESTION_MESSAGE,
                                             null,
                                             options,
                                             options[0])];
}

rule "Do you want to avoid using much of your brain?"
	then
		insert(new Choice("Do you want to avoid using much of your brain?", ["Yes", "No"] , ""));
end

rule "ask"
	when
		c : Choice(decision == "")
	then
		c.setDecision(ask(frame, c));
		update(c)
end

rule "How are your reflexes?"
	when
		c : Choice()
	then
    System.out.println(c.getAnswers());
		if(c.getDecision() == c.getAnswers()[0]) {
			insert(new Choice("How are your reflexes?", ["Yes", "No"], ""));
		}
end

